[workspace]
members = [
    "crates/lammps",
    "tools/adf",
    "tools/blob",
    "tools/blob_5",
    "tools/carbon-structure-analysis",
    "tools/component-shift",
    "tools/crater-analysis",
    "tools/density-distribution",
    "tools/detect-sputtered",
    "tools/rdf",
    "tools/remove-sputtered",
    "tools/rim-analysis",
    "tools/sputtered-analysis",
    "tools/surface-analysis",
    "tools/surface-heights-radial",
    "tools/zero-lvl",
]
resolver = "2"

[workspace.dependencies]
kd-tree = "0.6.0"
anyhow = "1.0.95"
itertools = "0.14.0"
colorgrad = "0.7.0"
clap = { version = "4.5.20", features = ["derive"] }
plotters = "0.3.7"
log = "0.4.25"
env_logger = "0.11.6"
rayon = "1.10.0"
geomutil_util = { git = "https://github.com/denisstrizhkin/geomutil-rust.git", version = "0.1.2", rev="0fa0ba0c8e767801681e3458e8402d12d22b8b4d" }
