[package]
name = "lammps-util-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.5"

[workspace]
members = ["density-distribution"]

[workspace.dependencies]
clap = { version = "4.5.20", features = ["derive"] }
plotters = "0.3.7"
