[package]
name = "rim-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
lammps-util = { workspace = true }
log = { workspace=true }
itertools = { workspace=true }
env_logger = { workspace=true }
anyhow = { workspace = true }
clap = { workspace = true }
geomutil_util = { workspace = true }
