[package]
name = "surface-heights-radial"
version = "0.1.0"
edition = "2024"

[dependencies]
lammps-util-rust = { path = "../"}
anyhow = { workspace=true }
clap = { workspace=true }
geomutil_util = { workspace=true }

