[package]
name = "carbon-structure-analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
lammps-util-rust = { path = "../"}
kd-tree = { workspace=true }
log = { workspace=true }
env_logger = { workspace=true }
anyhow = { workspace = true }
clap = { workspace = true }
