[package]
name = "crater-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
lammps-util-rust = { path = "../"}
kd-tree = { workspace=true }
anyhow = { workspace = true }
clap = { workspace = true }
