[package]
name = "density-distribution"
version = "0.1.0"
edition = "2021"

[dependencies]
lammps-util-rust = { path = "../"}
clap = { workspace = true }
plotters = { workspace = true }
geomutil = "0.1.1"
